services:
  db:
    image: postgres:18
    container_name: nestjs-template-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - nestjs-template_postgres:/var/lib/postgresql
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    networks:
      - management_network

  redis:
    image: redis:8.0
    container_name: nestjs-template-redis
    restart: unless-stopped
    volumes:
      - nestjs-template_redis:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - management_network

volumes:
  nestjs-template_postgres:
  nestjs-template_redis:

networks:
  management_network:
    external: true
